replicaCount: 1

image:
  repository: ghcr.io/chornberger-c2c/mockup-webshop
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: shop.localdomain
      paths:
        - path: /
          pathType: Prefix
  tls: []  # add certs here if needed
