image:
  repository: ghcr.io/chornberger-c2c/mockup-webshop
  tag: "1.3.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: "50m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: shop.herrhornberger.de
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - shop.herrhornberger.de
      secretName: shop-tls

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 5
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 10
          periodSeconds: 5
        - type: Percent
          value: 300
          periodSeconds: 5
    scaleDown:
      stabilizationWindowSeconds: 0
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100
          periodSeconds: 5
        - type: Pods
          value: 10
          periodSeconds: 5

