replicaCount: 1

image:
  repository: ghcr.io/chornberger-c2c/mockup-webshop
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

ingress:
  enabled: false
  # host: webshop.local
  # annotations: {}
  # tls: []

